--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pod-frontend
spec: 
  replicas: 1 # Defaults to 1
  selector: 
    matchLabels: 
      app: vue-end # key: value
  template: 
    metadata: 
      labels: 
        app: vue-end # key: value
    spec: 
      containers: 
        - 
          image: chendixi/dcan-vue:latest
          name: dcan-vue
          imagePullPolicy: Never
          ports: 
            - 
              containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-backend
spec:
  selector:
    matchLabels:
      app: fastapi-end
  template:
    metadata:
      labels:
        app: fastapi-end
    spec:
      containers:
        - name: dcan-fastapi
          image: chendixi/dcan-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
