---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: frontend-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: vue-end
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    run: backend-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: fastapi-end
  type: LoadBalancer
